### ISSUE TITLE
Graph2d groups properties not working

### ISSUE THREAD

**Issue by cassiamani** [sjmallon/vue-visjs#4]
Hello everyone,

In graph2d component, the group properties as content, options, className... not working, follow the link bellow:

codesandbox sample: https://codesandbox.io/s/gracious-chandrasekhar-l7i1q?file=/src/App.vue:383-609

notice that group names (content: 'name group') not draw in timeline graph2d.

**Comment by sjmallon** [comment]
Hi

Yes, unfortunately  there seems to be [an upstream bug](https://github.com/visjs/vis-timeline/issues/463) causing this.  You can see the problem in their own [example page](https://visjs.github.io/vis-timeline/examples/graph2d/)! Once there are updates to the upstream visjs packages, I'll up-issue this package.

**Comment by cassiamani** [comment]
really, i dont't noticed the bug on the example page, but I will wait for bug fix from visjs,

thanks so much @sjmallon

**Comment by cassiamani** [comment]
I found the solution, the id property must be of type string, not number, follow the explanation [here](https://github.com/visjs/vis-timeline/issues/463#issuecomment-668007906)

**Comment by sjmallon** [comment]
Fixed in >=v0.4.1
