### ISSUE TITLE
You may have an infinite update loop in watcher with expression "options"

### ISSUE THREAD

**Issue by yrx0823** [sjmallon/vue-visjs#6]
<Network style="height:100%;" ref="network" :nodes="nodes" :edges="edges" :options="options" ></Network>

**Comment by sjmallon** [comment]
Please provide more specific details and ideally a minimal example of erroneous behaviour.

**Comment by takada-s** [comment]
I encountered the same problem and found the condition to reproduce. 

just add following `layout` option into `network` sample at ` vue-visjs/examples/src/App.vue`

```json

        edges: { smooth: false },
        layout: {
          hierarchical: {
            enabled:true,
          }
        },
```
