### ISSUE TITLE
Unused dependencies

### ISSUE THREAD

**Issue by io12** [sjmallon/vue-visjs#7]
This package has many unused dependencies. The [depcheck](https://www.npmjs.com/package/depcheck) tool lists them as
```
Unused dependencies                                                            
* @egjs/hammerjs                                                               
* canvas
* core-js
* keycharm
* moment
* propagating-hammerjs
* uuid
* vis-util
* vue-runtime-helpers
Unused devDependencies
* @vue/cli-plugin-babel
* @vue/cli-plugin-eslint
* @vue/cli-plugin-unit-jest
* @vue/cli-service
* babel-eslint
* eslint
* eslint-plugin-prettier
* fibers
* node-sass
* prettier
* rollup
* rollup-plugin-node-resolve
* sass
* sass-loader
* vue-template-compiler
```

One of these packages, `canvas` has binary dependencies that need to be installed through a system package manager like `apt-get`, which is inconvenient for an unused dependency. It would be really helpful if you could fix this. Thanks!

**Comment by sjmallon** [comment]
Thanks for identifying this @io12.  Most of these are peer dependencies of required packages, however you are right about canvas: it should be a devDependency.  Fixed in 0.4.2.
